config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'homes#show'
  resources :users, only: [:show, :edit, :update]
  resources :posts, only: [:new, :create]
  resource :relationships, only: [:create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, :body, presence: true
  belongs_to :user
  has_many :taggings, dependent: :destroy
  has_many :tags, through: :taggings
  delegate :username, to: :user

  def self.tagged_with(name)
    Tag.find_by!(name: name).posts
  end

  def all_tags=(names)
    tags_array = names.split(",").map(&:strip)

    self.tags = tags_array.map do |name|
      Tag.where(name: name).first_or_create!
    end
  end

  def all_tags
    tags.map(&:name).join(", ")
  end
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"

  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :taggings, dependent: :destroy
  has_many :posts, through: :taggings 
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :post
  belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts, dependent: :destroy

  has_many :passive_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :passive_relationships, source: :follower

  has_many :active_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followings, through: :active_relationships, source: :followed

  def follow(other_user)
    active_relationships.create(followed_id: other_user.id)
  end

  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  def following?(other_user)
    following_ids.include?(other_user.id)
  end

  validates :username, presence: true
  mount_uploader :avatar, AvatarUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  def current_user?(user)
    current_user.id == user.id
  end
  helper_method :current_user?

  protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :email, :password, :password_confirmation, :remember_me])
      devise_parameter_sanitizer.permit(:sign_in, keys: [:login, :username, :email, :password, :remember_me])
      devise_parameter_sanitizer.permit(:account_update, keys: [:username, :email, :password, :password_confirmation, :current_password])
    end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def show
    @posts = Post.all
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.new(post_params)
    if @post.save
      redirect_to root_path
    else
      render :new
    end
  end

  private

    def post_params
      params.require(:post).permit(:title, :body, :all_tags)
    end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user

  def create
    current_user.follow(@user)
    redirect_to @user
  end

  def destroy
    current_user.unfollow(@user)
    redirect_to @user
  end

  private

    def set_user
      @user = User.find(params[:user_id])
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:edit, :update]
  before_action :check_authorization, only: [:edit, :update]
  before_action :set_user

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to @user
    else
      flash.now[:alert] = "Something went wrong. Please try again."
      render :edit
    end
  end

  def show
    
  end

  private
    def check_authorization
      unless current_user.id == params[:id].to_i
        redirect_to root_url
      end
    end

    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:username, :avatar, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def avatar_for(user, options = { size: 80 })
    size = options[:size]
    if user.avatar?
      image_tag user.avatar.url(:thumb), width: size, class: "avatar_image"
    else
      image_tag "default-avatar.jpg", width: size, class: "avatar_image"
    end
  end
end

app/views/homes/show.html.erb
<div class="col-md-6 col-md-offset-1">
  <h1>This is my app Gist The Facts</h1>

  <div class="posts">
    <%= render @posts %>
  </div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <%= link_to "Gist The Facts", root_path, class: "navbar-brand" %>
    <ul class="nav navbar-nav navbar-right">
      <li class="nav-button"><%= link_to "Write a gist", new_post_path, class: "button" %></li>
      <% if user_signed_in? %>
        <li class="current-user-avatar"><%= link_to(avatar_for(current_user, size: 35), current_user) %></li>
        <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
      <% else %>
        <li class="nav-button"><%= link_to "Sign in / Sign up", new_user_session_path, class: "button" %></li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GistTheFacts</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <div class="container">
      <%= yield %>
    </div>


  </body>
</html>

app/views/posts/_post.html.erb
<div class="post-panel">
  <%= avatar_for(post.user, size: 40) %>
  <%= link_to post.username, post.user %>
  <h3><%= post.title %></h3>
  <%= post.body %>
  <p><%= post.all_tags %></p>
</div>

app/views/posts/new.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h1>New Gist</h1>

    <%= form_for @post do |f| %>
      <% if @post.errors.any? %>
        <div class="error">
          <h2>
            <%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:
          </h2>
          <ul>
            <% @post.errors.full_messages.each do |msg| %>
              <li>
                <%= msg %>
              </li>
            <% end %>
          </ul>

        </div>
      <% end %>
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :body %>
        <%= f.text_area :body, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :all_tags %>
        <%= f.text_field :all_tags, class: "form-control" %>
      </div>

      <%= f.submit "Publish" %>
    <% end %>
  </div>
</div>

app/views/users/edit.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h1>Edit Profile</h1>

    <%= form_for(@user, html: { multipart: true }) do |f| %>
      <div class="form-group">
        <%= f.file_field :avatar, autofocus: true, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :username %><br />
        <%= f.text_field :username, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :description %><br />
        <%= f.text_area :description, class: "form-control" %>
      </div>

      <div class="actions">
        <%= f.submit "Update" %>
      </div>
    <% end %>

    <%= link_to "Back", :back %>
  </div>
</div>

app/views/users/show.html.erb
<h1>Profile for <%= @user.username %></h1>
<%= avatar_for(@user) %>
<%= @user.description %>

<% if user_signed_in? && current_user?(@user) %>
  <%= link_to "Edit profile", edit_user_path %>
<% end %>

<% if user_signed_in? && !current_user?(@user) %>
  <% if current_user.following?(@user) %>
    <%= button_to "Unfollow", relationships_path(user_id: @user.id), method: :delete, class: "button" %>
  <% else %>
    <%= button_to "Follow", relationships_path(user_id: @user.id), class: "button" %>
  <% end %>
<% end %>